name: Frontend build and push to ECR

on:
  push:
    branches:
      - feature

env:
  aws_region: ca-central-1
  
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Check Code
      uses: actions/checkout@v2

    - name: Get the date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"
    
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tag: CodingGround_Frontend:latest
        file: ./Dockerfile
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ env.aws_region }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    
    - name: Push Image to ECR
      run: |
        docker tag CodingGround_Frontend:latest ${{ env.ecr_url }}:${{ steps.tag.outputs.date }}
        docker push ${{ env.ecr_url }}:${{ steps.tag.outputs.date }}
