name: Frontend build and push to ECR

on:
  push:
    branches:
      - feature

env:
  ecr_url: 503237308475.dkr.ecr.ca-central-1.amazonaws.com/coding-ground-ecr
  role_arn: arn:aws:iam::503237308475:role/BSDEV16-ECS-AccessRole
  aws_region: ca-central-1
  
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Check Code
      uses: actions/checkout@v2

    - name: Get the date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"
    
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tag: CodingGround_Frontend:latest
        file: ./Dockerfile
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.aws_region }}
        role-to-assume: ${{ env.role_arn }}
    
    - name: Push Image to ECR
      run: |
        docker tag CodingGround_Frontend:latest ${{ env.ecr_url }}:${{ steps.tag.outputs.date }}
        docker push ${{ env.ecr_url }}:${{ steps.tag.outputs.date }}
